### ISSUE TITLE
Some animated emotes are slow motion

### ISSUE THREAD

**Issue by CycIoneTM** [chatsen/chatsen#49] opened 2021-06-12 04:30 UTC
https://user-images.githubusercontent.com/27637025/121766202-06477f00-cb16-11eb-87a9-da0c2c422c5d.mp4

**Comment by williambulin** [comment] 2021-06-12 12:18
Duplicate of https://github.com/chatsen/chatsen/issues/21.

**Closed by williambulin** 2021-06-12 12:18 UTC
